{"sid": "e9ec6c9055c84ffda2110f0c6858797a", "uid": null, "qid": "1b0cb1e99d154f58a6a4d1e59dbe0456", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [1b0cb1e99d154f58a6a4d1e59dbe0456]\nTraceback (most recent call last):\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/workspaces/Openfabic/app/main.py\", line 57, in execute\n    logging.info(f\"User prompt: {prompt}\")\n                                 ^^^^^^\nNameError: name 'prompt' is not defined\n", "created_at": "2025-06-08T09:43:56.940140"}], "status": "FAILED", "created_at": "2025-06-08T09:43:53.278023", "updated_at": "2025-06-08T09:43:56.940165", "finished": true}